wrap = (type,attr,b...) ->
	b = b.join ""
	if attr == {} 
		"<#{type}>#{b}</#{type}>"
	else 
		attr = "#{key}=\"#{value}\"" for key,value of attr
		return "<#{type} #{attr}>#{b}</#{type}>"

export table = (attr,b...) -> wrap 'table',attr,b...
export thead = (attr,b...) -> wrap 'thead',attr,b...
export th    = (attr,b...) -> wrap 'th',attr,b...
export tr    = (attr,b...) -> wrap 'tr',attr,b...
export td    = (attr,b...) -> wrap 'td',attr, b...
export a     = (attr,b)    -> wrap 'a',attr, b
export div   = (attr,b...) -> wrap 'div',attr,b...
export pre   = (attr,b...) -> wrap 'pre',attr,b...
export p     = (attr,b...) -> wrap 'p',attr,b...
export h2    = (attr,b...) -> wrap 'h2',attr,b...
